### PR TITLE
Project Duplicate Bug Fixing

### PR DESCRIPTION
**Pull request by nadiln**
## Description

When duplicating project, the duplicate is happening but the project tasks related to that particular project is not copying . instead of that some other tasks are copying to duplicated project. I found that duplicateid is parsed to Save.php but Save.ph is looking for relate_id which is a bug.

## How To Test This

Try duplicating a project , it does not duplicate project tasks
## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Hi @nadiln Thanks for the contribution! However, this PR is to your own personal repository and not the main SuiteCRM repo. To create a pull request to the hotfix branch of SuiteCRM you will want to go here: 

https://github.com/salesagility/SuiteCRM/pulls

Click "New Pull Request" at the top right and you should see a screen like this: 
github-help

You want to select the "hotfix" branch with the button on the left and then select your own personal branch "nadil-project-duplicate-bug-fix" on the right. Thanks.

**Comment by nadiln** [comment]
@Dillon-Brown Thank you for your guidance! as you said I can see the changes on my repository but when I make the pull request I don't see my branch on right hand side dropdown. Why is that? Please help me I am curiously waiting for to contribute to SuiteCRM.

**Comment by Dillon-Brown** [comment]
@nadiln My apologies, I had the wrong link/image. The pull request will be made from your own branch but commited to the SalesAgility repo. You make the pull request from your own repository that you will find on your profile and then clicking "pull request" next to "compare": 
git-info-2

Then you will want to select SalesAgility/SuiteCRM on the left along with the "hotfix" branch and then your own repo and branch on the right. In this case I am creating a pull request to the hotfix branch with the changes I made in my jjwg_maps_cleanup branch:
git-info

**Comment by nadiln** [comment]
@Dillon-Brown It's Ok. Once again thanks for your guidance! Now I have made the pull request..

**Pull request merged**
